//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FriscoDev.Application.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScheduleOperations
    {
        public string Name { get; set; }
        public byte DisplayType { get; set; }
        public string Content { get; set; }
        public int Hash { get; set; }
        public int PMG_ID { get; set; }
    }
}
