//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FriscoDev.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUSTOMER
    {
        public string CS_ID { get; set; }
        public string CS_NAME { get; set; }
        public string CS_ADDRESS { get; set; }
        public decimal CS_COORDINATE_X { get; set; }
        public decimal CS_COORDINATE_Y { get; set; }
        public string CS_COUNTRY_ID { get; set; }
        public string CS_CITY_ID { get; set; }
        public int CS_POSTAL_CODE { get; set; }
        public string CS_PHONE1 { get; set; }
        public string CS_PHONE2 { get; set; }
        public string CS_CELL_PHONE1 { get; set; }
        public string CS_CELL_PHONE2 { get; set; }
        public int CS_COUNTRY_PHONE_CODE { get; set; }
        public string CS_EMAIL { get; set; }
        public string CS_TIME_ZONE { get; set; }
        public string CS_LANGUAUE_ID { get; set; }
        public bool CS_ACTIVED { get; set; }
        public Nullable<System.DateTime> CS_ADD_TIME { get; set; }
        public Nullable<System.DateTime> CS_UPDATE_TIME { get; set; }
    }
}
