//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FriscoDev.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class EVENT
    {
        public string EN_ID { get; set; }
        public int EN_TYPE { get; set; }
        public string DEV_ID { get; set; }
        public int VEH_TYPE_ID { get; set; }
        public System.DateTime EN_TIME { get; set; }
        public decimal EN_SPEED { get; set; }
        public string EN_DESC { get; set; }
    }
}
