//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FriscoDev.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class LeasedDeviceLog
    {
        public int Id { get; set; }
        public string IMSI { get; set; }
        public Nullable<int> PMDID { get; set; }
        public string BelongName { get; set; }
        public System.DateTime LeasedStartDate { get; set; }
        public System.DateTime LeasedEndDate { get; set; }
        public System.DateTime CreateTime { get; set; }
    }
}
