//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FriscoDev.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOG
    {
        public int LOG_ID { get; set; }
        public int LOG_TYPE_ID { get; set; }
        public string LOG_DES { get; set; }
        public string LOG_USER_NAME { get; set; }
        public Nullable<System.DateTime> LOG_TIME { get; set; }
    }
}
