//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FriscoDev.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DbEntities : DbContext
    {
        public DbEntities()
            : base("name=DbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Account> Account { get; set; }
        public virtual DbSet<Account_bak> Account_bak { get; set; }
        public virtual DbSet<CUSTOMER> CUSTOMER { get; set; }
        public virtual DbSet<DEVICE> DEVICE { get; set; }
        public virtual DbSet<DeviceNames> DeviceNames { get; set; }
        public virtual DbSet<EVENT> EVENT { get; set; }
        public virtual DbSet<EVENT_TYPE> EVENT_TYPE { get; set; }
        public virtual DbSet<LANGUAGE> LANGUAGE { get; set; }
        public virtual DbSet<LOG> LOG { get; set; }
        public virtual DbSet<LOG_TYPE> LOG_TYPE { get; set; }
        public virtual DbSet<PMD> PMD { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TIMEZONE> TIMEZONE { get; set; }
        public virtual DbSet<TimeZoneInfo> TimeZoneInfo { get; set; }
        public virtual DbSet<CITY> CITY { get; set; }
        public virtual DbSet<COUNTRY> COUNTRY { get; set; }
        public virtual DbSet<DeviceLocation> DeviceLocation { get; set; }
        public virtual DbSet<LeasedDeviceLog> LeasedDeviceLog { get; set; }
        public virtual DbSet<MESSAGE> MESSAGE { get; set; }
        public virtual DbSet<PMD_BAK1106> PMD_BAK1106 { get; set; }
        public virtual DbSet<PMDConfig> PMDConfig { get; set; }
        public virtual DbSet<SiteConfig> SiteConfig { get; set; }
        public virtual DbSet<StatsLog> StatsLog { get; set; }
        public virtual DbSet<StatsLog1001> StatsLog1001 { get; set; }
        public virtual DbSet<UserLoginInfo> UserLoginInfo { get; set; }
        public virtual DbSet<USERTYPE> USERTYPE { get; set; }
    }
}
